front/infotec/apps/documents/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
app_name = 'doc'
urlpatterns = [
    path('dashboard/',views.home,name='dashboard'),
    path('list/',views.DocumentList,name='DocumentView'),
    path('closeDocuments',views.DocumentListClose,name="documentCloseView"),
    path('detailList/',views.docList,name='DocumentList'),
    path('closeList',views.docListClose,name='closeList'),
    path('new/',views.new,name='new'),
    path('save',views.saveDocument,name='saveDocument'),
    path('details/<int:id>',views.details,name='detalView'),
    path('details/statusUpdate',views.statusUpdate,name="statusUpdate"),
    path('saveResponse',views.saveResponse,name="saveResponse"),
    path('close',views.documentClose,name="DocumentClose"),
    path('details/getDetail', views.getDocumentDetails, name="DocumentDetail"),
]

front/infotec/infotec/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('apps.login.urls')),
    path('documents/',include('apps.documents.urls')),
]

front/infotec/apps/documents/models.py
from django.db import models

# Create your models here.

front/infotec/apps/documents/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    folio = forms.CharField(max_length=50)
    usrAsign = forms.IntegerField()
    comment = forms.CharField(max_length=200)
    area = forms.CharField(max_length=200)
    emisor = forms.CharField(max_length=200)
    docType = forms.CharField(max_length=200)
    receptionDate = forms.CharField()
    priority = forms.IntegerField()
    filename = forms.CharField(max_length=100)
    file = forms.FileField()

class UploadFileResponse(forms.Form):
    doctitle = forms.CharField(max_length=50)
    docType = forms.IntegerField()
    filename = forms.CharField(max_length=100)
    processId = forms.IntegerField()
    file = forms.FileField()

front/infotec/apps/documents/views.py
from django.shortcuts import render
from . import service
from django.urls import reverse
import json
import base64
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from .forms import UploadFileForm,UploadFileResponse
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from . import utils
from datetime import datetime


# Create your views here.

def home(request):
    try:
        request.session['usr']
    except:
        return HttpResponseRedirect(reverse('login:loginView'))
    
    user = request.session['usr']
    m = service.getMetrica(user.get('id_usuario'))
    context ={
        'm':m,
    }
    return render(request,'home.html',context)


def DocumentList(request):
  
    try:
        request.session['usr']
    except:
        return HttpResponseRedirect(reverse('login:loginView'))
    return render(request,'document/home.html',{})

def DocumentListClose(request):
    try:
        request.session['usr']
    except:
        return HttpResponseRedirect(reverse('login:loginView'))
    return render(request,'document/closedHome.html',{})

def new(request):
    try:
        request.session['usr']
    except:
        return HttpResponseRedirect(reverse('login:loginView'))
    
    isCreate = request.session['isResponse']
    if isCreate == False:
        return HttpResponseRedirect(reverse('doc:DocumentView'))

    

    context = {
        'priority' : service.getPriority(),
        'users' : service.getUsers()
    }
    
    return render(request,'document/new.html',context)

def details(request,id):
    try:
        request.session['usr']
    except:
        return HttpResponseRedirect(reverse('login:loginView'))
    request.session['docId'] = id
    user = request.session['usr']
    usrId = user.get('id_usuario')
    aux =  service.getDetails(usrId,id)

    #print(aux)
    
    context ={
        'processId':id,
        'data': aux,
        'type': service.getDocumentType(),
    }
    
    return render(request,'document/details.html',context)

##equests
@csrf_protect
def saveDocument(request):
    data = dict()
    if request.method == 'POST':
        form = UploadFileForm(request.POST,request.FILES)
        if form.is_valid():
            user = request.session['usr']
            filename = request.POST['filename']
            idUser = user.get('id_usuario')
            asunto = request.POST['title']
            comentario = request.POST['comment']
            folio = request.POST['folio']
            idAsignar = request.POST['usrAsign']
            area = request.POST['area']
            emisor = request.POST['emisor']
            docType = request.POST['docType']
            priority = request.POST['priority']
            receptionDate = request.POST['receptionDate']

            receptionDate = receptionDate+":00"

            name = filename
            name = name.replace(".pdf","")
            name = name.replace(".PDF","")
            filename = filename.replace(" ","_")

            dat = {
                "evento":[
                    {
                        "idEvento": 0,
                        "idPrioridad": priority,
                        "idUsr": idUser
                    }
                ],
                "detalle":[
                    {
                        "asunto": asunto,
                        "comentarios": comentario,
                        "folio": folio,
                        "idUsrd":idAsignar,
                        "area" : area,
                        "emisor" : emisor,
                        "fechaRecepcion" : receptionDate,
                        "tipo" : docType,
                        "respuesta": ""
                    }
                ],
                "informacion":[
                    {
                    "documento": filename,
                    "nombre" : name
                    }
                ]
            }
            
            utils.handle_upload_file(request.FILES['file'],filename)
            doc = service.saveDocument(dat)
            #print(doc)
            data['message'] = 'ok'
            data['status'] = True
            data['errorMsg'] = doc.get('errorMsg')
            #return JsonResponse(data)
            
        else:
            data['errorMsg'] = ""
            data['status'] = False
            data['message'] = 'llene todos los campos'
            #return JsonResponse(data)
    else:   
        data['errorMsg'] = ""
        data['status'] = False
        data['message'] = "Petición invalida"

    return JsonResponse(data)

def getDocumentDetails(request):

    id = request.session['docId']
    user = request.session['usr']
    usrId = user.get('id_usuario')
    aux =  service.getDetails(usrId,id)
    
    documents = utils.documentDetails(aux)
    data = dict()
    data['doc'] = documents
    del request.session['docId']
    return JsonResponse(data)


def docList(request):
    user = request.session['usr']
    doc = service.getDocuments(user.get('id_usuario'))
   ## docaux = doc.get(0).get('idEvento')
    #print(doc.get('detdoc'))
    idEvento = 1
    data = dict()
    for t in doc.get('detdoc'):
        
        if t.get('idEvento') == 0:
            idEvento = 0
            break
    if idEvento == 0:
        data['data'] = ''
    else:
        data['data'] = doc.get("detdoc")    
    
    return JsonResponse(data)

def docListClose(request):

    user = request.session['usr']
    doc = service.getDocumentsClose(user.get('id_usuario'))
    idEvento = 1
    data = dict()
    for t in doc.get('detdoc'):
        
        if t.get('idEvento') == 0:
            idEvento = 0
            break
    if idEvento == 0:
        data['data'] = ''
    else:
        data['data'] = doc.get("detdoc")    
    
    return JsonResponse(data)

@csrf_protect
def statusUpdate(request):
    data = dict()
    if request.method == 'POST':
        ##user = request.session['usr']
        id = request.POST['id']
        status = service.statusUpdate(id)
        #print(status)
        #print("holi")
        if status.get('idEvento') == 0:
            data['status'] = False
            data['message'] = status.get('errorMsg')
        else:
            data['status'] = True
            data['message'] = 'Estado actualizado con exito!'
    else:
        data['status'] = False
        data['message'] = 'Petición invalida!'

    return JsonResponse(data)

     
@csrf_protect
def saveResponse(request):
    data = dict()
    if request.method == 'POST':
        form = UploadFileResponse(request.POST,request.FILES)
        if form.is_valid():
            process = request.POST['processId']
            name = request.POST['doctitle']
            idType = request.POST['docType']
            filename = request.POST['filename']
            d = datetime.now()

            dat={
                 "documento": filename,
                 "fechaAdd": d.strftime("%Y/%m/%d %H:%M:%S"),
                 "idEvento": process,
                 "idDocumento": 0,
                 "idTipo":idType,
                 "nombre":name
            }
            utils.handle_upload_file(request.FILES['file'],filename)
            doc = service.addResponse(dat)

            data['status'] = True
            data['message'] = "documento subido con éxito!"
            data['resId'] = doc.get("idDocumento")

        else:
            data['resId'] = "0"
            data['status'] = False
            data['message'] = "llene todos los campos"    
    else:
        data['resId'] = "0"
        data['status'] = False
        data['message'] = "Petición invalida"

    return JsonResponse(data)


@csrf_protect
def documentClose(request):
    data = dict()
    if request.method=='POST':
        idToClose = request.POST['id']
        doc = service.documentClose(idToClose)

        if doc.get('errorMsg') == "":
            data['status'] = True
            data['message'] = "Documento cerrado con exito!"
        else:
            data['status'] = False
            data['message'] = doc.get('errorMsg')
    
    else:
        data['status'] = False
        data['message'] = 'Petición invalida'

    return JsonResponse(data)

front/infotec/apps/documents/templates/document/closedHome.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mis documentos Cerrados {% endblock %}
{% block content %}

        
<div class="row">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    Mis Incidentes Cerrados
                    
                </div>
                <div class="row">
                    <table class="striped centered responsive-table" id="IncidentTable">
                        <thead>
                            <tr>
                                <th>Folio</th>
                                <th>Nombre</th>
                                <th>Área</th>
                                <th>Fecha de creación</th>
                                <th>Fecha recepción</th>
                                <th>Fecha de cierre</th>
                                <th>Estatus</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrajs %}
<script src="{% static 'js/document/closedList.js' %}"></script>
{% endblock %}

front/infotec/apps/documents/templates/document/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Detalles {% endblock %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'css/pdfCss.css' %}">
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
{% endblock %}
{% block content %}
<div id="upload" style="visibility: hidden;">
    <img src="{% static 'img/upload.gif' %}"  width="30%"/>
</div>
<div id="load" style="visibility: hidden;">
    <img src="{% static 'img/load.gif' %}" width="30%" />
</div>
<div class="row" style="padding: 50px 150px 0px 150px;">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    {% if data.estadoTarea == "Terminada" %}
                        <a href="{% url 'doc:documentCloseView' %}"><i class="material-icons left">keyboard_backspace</i></a>Documento <b>'{{ data.folio }}'</b>
                    {% else %}
                        <a href="{% url 'doc:DocumentView' %}"><i class="material-icons left">keyboard_backspace</i></a>Documento <b>'{{ data.folio }}'</b>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="input-field col s4">
                        <input disabled id="title" name="title" type="text" class="validate"/>
                        <label for="title" id="ltitle">Titulo</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="folio" type="text" class="validate"/>
                        <label id="lfolio" for="folio">Folio</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="Pstatus" type="text" class="validate" />
                        <label id="lPstatus" for="Pstatus">Estado de proceso</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="Tstatus" type="text" class="validate"/>
                        <label id="lTstatus" for="Tstatus">Estado de tarea</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="area" type="text" class="validate"/>
                        <label id="larea" for="area">Area</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="emisor"  type="text" class="validate"/>
                        <label id="lemisor" for="emisor">Emisor</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="tipo"  type="text" class="validate"/>
                        <label id="ltipo" for="tipo">Tipo</label>
                    </div>
                    <div class="input-field col s4">
                        <input disabled id="prioridad"  type="text" class="validate"/>
                        <label id="lprioridad" for="tipo">Prioridad</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <textarea id="comentarios" disabled class="materialize-textarea"></textarea>
                        <label id="lcomentarios" for="comentarios">Comentarios</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if request.session.isResponse %}
<div class="row" style="padding:0px 150px 0px 150px;">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    {%  csrf_token %}
                    {% if data.estadoTarea == "Asignado" %}
                        <h5>Actualizar estado</h5>
                        <p><h6>Actualizar estado a "En revisión"</h6></p>
                        <button class="btn waves-effect waves-light" type="button" onclick="statusUpdate({{ data.idEvento }})">Actualizar</button>
                    {% endif %}
                    {% if data.estadoTarea == "En revisión" %}
                        <h5>Respuesta</h5>
                        
                        <form id="responseUpload" >
                            {%  csrf_token %}
                            <div class="row">

                                <div class="input-field col s12">
                                    <i class="material-icons prefix">title</i>
                                    <input class="validate" id="doctitle" type="text" name="doctitle" required />
                                    <label for="doctitle" data-error="wrong" data-success="right" class="center-align">nombre</label>
                                </div>
                                
                                <div class="input-field col s6">
                                    <select id="docType" name="docType">
                                        <option value="0" disabled selected>Seleccione documento</option>
                                        {% for u in type %}
                                            {% if u.idTipo != 1 %}
                                                <option value="{{ u.idTipo }}">{{ u.tipo }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                    <label>Tipo Documento</label>
                                </div>
                                <div class="input-field col s6" hidden>
                                    <input class="validate" id="processId" type="text" name="processId" value="{{ processId }}" disabled/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="file-field input-field">
                                    <div class="btn white">
                                    <i class="material-icons md-dark">folder</i>
                                    <input type="file" id="file" name="file" accept="application/pdf" >
                                    </div>
                                    <div class="file-path-wrapper">
                                    <input class="file-path validate" type="text" id="filename" name="filename"/>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="center-align">
                                    <button id="saveResponse" class="btn center-align" type="button" onclick="upoloadResponse()">Guardar</button>
                                    <button class="btn waves-effect waves-light" type="button" onclick="openCloseModal({{ data.idEvento }})">Terminar</button>
                                </div>
                            </div>
                        </form>

                        <!-- div class="row">
                            <h5>Actualizar estado</h5>
                            <p><h6>Actualizar estado a "Terminado"</h6></p>
                            <button class="btn waves-effect waves-light" type="button" onclick="openCloseModal({{ data.idEvento }})">Actualizar</button>
                        </div -->
                        
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="row" style="padding: 0px 150px 0px 150px;">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    {{ data.nombre }}
                </div>
                <div class="row">
                    <div class="col s6">
                        <canvas id="pdf_canvas"></canvas>

                        <div class="row">
                            <div class="col s2">
                                <button class="m-button" id="prev_page"><i class="material-icons">keyboard_arrow_left</i></button>
                            </div>
                            <div class="col s2">
                                <button class="m-button" id="next_page"><i class="material-icons">keyboard_arrow_right</i></button>
                            </div>
                            <div class="col s1">
                                <span id="current_page_num"></span>
                            </div>
                            <div class="col s1">
                                de
                            </div>
                            <div class="col s1">
                                <span id="total_page_num"></span>
                            </div>
                            <div class="col s3">
                                <input type="text" id="page_num" />
                            </div>
                            <div class="col s1">
                                <button class="m-button" id="go_to_page"><i class="material-icons">search</i></button>
                            </div>
                        </div>
                    </div>
                    <div class="s6">
                        <div>
                            <h5 class="center-align">Documentos Complementarios</h4>
                        </div>
                        <div id="extraDoc">
                           
                        </div>
                        
                    </div>
                </div>               
            </div>
        </div>
    </div>
</div>

<!-- Modal Structure -->
<div id="canvasmodal" class="modal">
    <div class="modal-content">
      <h4>Respuesta</h4>
      <h5>Documento</h5>
      <canvas id="modal_pdf_canvas"></canvas>
      <div class="row">
        <div class="col s2">
            <button class="m-button" id="modal_prev_page"><i class="material-icons">keyboard_arrow_left</i></button>
        </div>
        <div class="col s2">
            <button class="m-button" id="modal_next_page"><i class="material-icons">keyboard_arrow_right</i></button>
        </div>
        <div class="col s1">
            <span id="modal_current_page_num"></span>
        </div>
        <div class="col s1">
            de
        </div>
        <div class="col s1">
            <span id="modal_total_page_num"></span>
        </div>
        <div class="col s3">
            <input type="text" id="modal_page_num" />
        </div>
        <div class="col s1">
            <button class="m-button" id="modal_go_to_page"><i class="material-icons">search</i></button>
        </div>
    </div>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>

  <!-- Modal Structure -->
  <div id="modalClose" class="modal">
    <div class="modal-content">
      <h4>Terminar proceso</h4>
      <p><b>Esta seguro de terminar proceso?</b></p>
      <p>Una vez terminado no podra responder con ningun archivo.</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Cancelar</a>
      <a href="#!" onclick="documentClose()" class="modal-close waves-effect waves-green btn-flat">Termiar</a>
    </div>
  </div>
          


    <p id="doc" name="doc" hidden></p>
        

{% endblock %}
{% block extrajs %}
<script src="{% static 'js/loader.js' %}"></script>
<script src="{% static 'js/pdf/pdf.js' %}"></script>
<script src="{% static 'js/pdf/pdf.worker.js' %}"></script>
<script src="{% static 'js/pdf/myPdf.js' %}"></script>
<script src="{% static 'js/document/details.js' %}"></script>

{% endblock %}

front/infotec/apps/documents/templates/document/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Mis documentos {% endblock %}
{% block content %}


{% if request.session.create %}
<div class="fixed-action-btn">
    <a href="{% url 'doc:new' %}" class="btn-floating btn-large">
      <i class="large material-icons">add</i>
    </a>
    
</div>
{% endif %}
        
<div class="row">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    Mis Incidentes
                    
                </div>
                <div class="row">
                    <table id="IncidentTable">
                        <thead>
                            <tr>
                                <th>Folio</th>
                                <th>Nombre</th>
                                <th>Área</th>
                                <th>Tarea</th>
                                <th>Fecha de creación</th>
                                <th>Fecha recepción</th>
                                <th>Estatus</th>
                                <th>Prioridad</th>
                                <th>id 1</th>
                                <th>id 2</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrajs %}
<script src="{% static 'js/document/list.js' %}"></script>
{% endblock %}

front/infotec/apps/documents/templates/document/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %} New {% endblock %}
{% block extracss %}
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
{% endblock %}
{% block content %}
<div id="upload" style="visibility: hidden;">
    <img src="{% static 'img/upload.gif' %}"  width="30%"/>
</div>
<div class="row" style="padding: 50px 150px 0px 150px;">
    <div class="col m12 s12">
        <div class="card z-depth-5">
            <div class="card-content">
                <div class="card-title">
                    <a href="{% url 'doc:DocumentView' %}"><i class="material-icons left">keyboard_backspace</i></a>Nuevo documento
                </div>
                <form id="formUpload">
                    {%  csrf_token %}
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">title</i>
                            <input class="validate" id="title" type="text" name="title" required />
                            <label for="title" data-error="wrong" data-success="right" class="center-align">nombre</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">assignment</i>
                            <input class="validate" id="folio" type="text" name="folio" required />
                            <label for="folio" data-error="wrong" data-success="right" class="center-align">Folio</label>
                        </div>
                        <div class="input-field col s6">
                            <select id="usrAsign" name="usrAsign">
                                <option value="0" disabled selected>Seleccione usuario</option>
                                {% for u in users %}
                                    {% if u.id_usuario != request.session.usr.id %}
                                        <option value="{{ u.id_usuario }}">{{ u.nombre }} {{u.paterno }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <label>Turnado a:</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">apartment</i>
                            <input class="validate" id="area" type="text" name="area" />
                            <label for="area">Área</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">assignment_ind</i>
                            <input class="validate" id="emisor" type="text" name="emisor"/>
                            <label for="emisor">Enviado por:</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">description</i>
                            <input class="validate" id="docType" type="text" name="docType"/>
                            <label for="docType">Tipo de documento:</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">date_range</i>
                            <input class="validate" id="receptionDate" type="text" name="receptionDate"/>
                            <label for="receptionDate">Fecha de recepción</label>
                        </div>
                        <div class="input-field col s6">
                            <select id="priority" name="priority">
                                <option value="0" disabled selected>Seleccione prioridad</option>
                                {% for u in priority %}
                                    
                                        <option value="{{ u.id_prioridad }}">{{ u.prioridad }}</option>
                                  
                                {% endfor %}
                            </select>
                            <label>Prioridad</label>
                        </div>
                        <div class="input-field col s12">
                            <i class="material-icons prefix">mode_comment</i>
                            <input class="validate" id="comment" type="text" name="comment" required />
                            <label for="comment" data-error="wrong" data-success="right" class="center-align">Comentarios</label>
                        </div>
                        
                        
                    </div>
                    <div class="row">
                        <div class="file-field input-field">
                            <div class="btn white">
                            <i class="material-icons md-dark">folder</i>
                            <input type="file" id="file" name="file" accept="application/pdf" >
                            </div>
                            <div class="file-path-wrapper">
                            <input class="file-path validate" type="text" id="filename" name="filename"/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="center-align">
                            <button id="saveNew" class="btn center-align" type="button" onclick="upoload()">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrajs %}
<script src="{% static 'js/materializedatetimepicker.js' %}"></script>
<script src="{% static 'js/document/saveDocument.js' %}"></script>
<script src="{% static 'js/loader.js' %}"></script>
{% endblock %}