front/infotec/apps/documents/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
app_name = 'doc'
urlpatterns = [
    path('dashboard/',views.home,name='dashboard'),
    path('list/',views.DocumentList,name='DocumentView'),
    path('closeDocuments',views.DocumentListClose,name="documentCloseView"),
    path('detailList/',views.docList,name='DocumentList'),
    path('closeList',views.docListClose,name='closeList'),
    path('new/',views.new,name='new'),
    path('save',views.saveDocument,name='saveDocument'),
    path('details/<int:id>',views.details,name='detalView'),
    path('details/statusUpdate',views.statusUpdate,name="statusUpdate"),
    path('saveResponse',views.saveResponse,name="saveResponse"),
    path('close',views.documentClose,name="DocumentClose"),
    path('details/getDetail', views.getDocumentDetails, name="DocumentDetail"),
]

front/infotec/apps/login/urls.py
from django.contrib import admin
from django.urls import path
from . import views 
app_name = 'login'
urlpatterns = [
    path('login/',views.loginView,name='loginView'),
    path('logout/',views.logout,name='logout'),
    path('sendLogin/',views.login, name="loginRequest"),
    path('code/<int:idUsr>',views.codeView, name="codeView"),
    path('validateCode',views.validateCode,name='validateCode'),
]

front/infotec/infotec/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('apps.login.urls')),
    path('documents/',include('apps.documents.urls')),
]

front/infotec/templates/base.html
<!-- templates/base.html-->
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} Django {% endblock %}</title> 
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet">
        {% block extracss %}
        {% endblock %}
    </head>
    <body>
        <ul id="DocDropdown" class="dropdown-content">
          <li><a href="{% url 'doc:DocumentView'%}" class="black-text">Documentos</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'doc:documentCloseView'%}" class="black-text">Documentos Cerrados</a></li>
        </ul>
        <nav class="white black-text">
            <div class="nav-wrapper">
                  <a href="{% url 'doc:DocumentView' %}" class="brand-logo"><img class="responsive-img valign profile-image-login custom-img" src="{% static '/img/infotec-logo.jpg' %}"></a>
                  <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'doc:dashboard' %}" class="black-text">Dashboard</a></li>
                    <li><a class="dropdown-trigger black-text" href="#!" data-target="DocDropdown">Documentos<i class="material-icons right">arrow_drop_down</i></a></li>
                    <li><a href="{% url 'login:logout' %}" class="black-text"><i class="material-icons right md-dark">exit_to_app</i>{{ request.session.usr.nombre }}</a></li>
                  </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="page-footer white">   
            <div class="footer-copyright">
              <div class="container">
              <p class="black-text"> © {% now "Y" %} Copyright Infotec </p>
              </div>
            </div>
          </footer>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'js/materialize.js' %}"></script>
        <script src="{% static 'js/moment.js' %}"></script>
        <script src="{% static 'js/moment-with-locales.js' %}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <script src="{% static 'js/base.js' %}"></script>
        {% block extrajs %}
        {% endblock %}
    </body>
</html>